# Generated by Django 4.2.7 on 2025-07-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('warehouse', 'Warehouse'), ('delivery', 'Delivery')], default='admin', max_length=20),
        ),
    ]
