# Generated by Django 4.2.7 on 2025-08-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
    ]
