# Generated by Django 4.2.7 on 2025-08-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250806_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_worker',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('warehouse_manager', 'Warehouse Manager'), ('warehouse_worker', 'Warehouse Worker'), ('warehouse', 'Warehouse Staff'), ('delivery', 'Delivery')], default='warehouse_worker', max_length=20),
        ),
    ]
