services:
  # Backend Django API
  - type: web
    name: internaloox-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn oox_system.wsgi:application"
    healthCheckPath: "/admin/"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: internaloox-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".render.com"

  # Frontend Static Site (React/Next.js)
  - type: web
    name: internaloox-frontend
    env: static
    plan: free
    buildCommand: npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: internaloox-db
    databaseName: internaloox
    user: internaloox