services:
  # Backend Django API
  - type: web
    name: internaloox
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn oox_system.wsgi:application -b 0.0.0.0:$PORT"
    healthCheckPath: "/admin/"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: internaloox-db
          property: connectionString

databases:
  - name: internaloox-db
    databaseName: internaloox
    user: internaloox