# Generated by Django 4.2.7 on 2025-07-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_for_order',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='default_quantity_unit',
            field=models.CharField(blank=True, default='unit', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Couch', 'Couch'), ('Mattress', 'Mattress'), ('Base', 'Base'), ('CoffeeTable', 'Coffee Table'), ('TVStand', 'TV Stand'), ('Set', 'Set'), ('Other', 'Other')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='production_time_days',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'model_code')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
