# Generated by Django 4.2.7 on 2025-07-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_color_fabric_remove_order_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
