# Generated by Django 4.2.7 on 2025-07-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitem_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='assigned_color_code',
            field=models.CharField(blank=True, default='', help_text='Color code from reference board', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='assigned_fabric_letter',
            field=models.CharField(blank=True, default='', help_text='Fabric code from reference board', max_length=1),
        ),
    ]
