# Generated by Django 4.2.7 on 2025-07-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orderitem_assigned_color_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deposit_paid_date',
            field=models.DateTimeField(blank=True, help_text='When deposit was paid - starts queue timer', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_completion_date',
            field=models.DateField(blank=True, help_text='Auto-calculated based on queue', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_priority_order',
            field=models.BooleanField(default=False, help_text='Owner-escalated priority order'),
        ),
        migrations.AddField(
            model_name='order',
            name='production_start_date',
            field=models.DateField(blank=True, help_text='When production actually started', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='queue_position',
            field=models.IntegerField(blank=True, help_text='Position in production queue', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, help_text='Set only when order is ready', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('deposit_pending', 'Deposit Pending'), ('deposit_paid', 'Deposit Paid - In Queue'), ('order_ready', 'Order Ready'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_production', 'In Production'), ('ready_for_delivery', 'Ready for Delivery')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('deposit_pending', 'Deposit Pending'), ('deposit_paid', 'Deposit Paid'), ('fully_paid', 'Fully Paid'), ('overdue', 'Overdue'), ('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('deposit_only', 'Deposit Only'), ('fifty_percent', '50% Paid')], default='deposit_only', max_length=20),
        ),
    ]
