# Generated by Django 4.2.7 on 2025-08-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_add_payment_transaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='orders_paym_order_i_95152d_idx',
            old_name='orders_pay_order_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='orders_paym_actor_u_15513a_idx',
            old_name='orders_pay_actor_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='orders_paym_payment_dc6ad8_idx',
            old_name='orders_pay_method_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='orders_paym_payment_de52d4_idx',
            old_name='orders_pay_status_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='available_colors',
            field=models.JSONField(blank=True, default=list, help_text='List of available colors for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='available_fabrics',
            field=models.JSONField(blank=True, default=list, help_text='List of available fabrics for this product'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_images',
            field=models.JSONField(blank=True, default=dict, help_text='Image URLs for each color variant'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_samples',
            field=models.JSONField(blank=True, default=dict, help_text='Sample images for each fabric type'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='proof_image',
            field=models.FileField(upload_to='payment_proofs/'),
        ),
    ]
