# Generated by Django 4.2.7 on 2025-08-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_allow_pdf_in_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='colorreference',
            table='orders_colorreference',
        ),
        migrations.AlterModelTable(
            name='fabricreference',
            table='orders_fabricreference',
        ),
    ]
