# Generated by Django 4.2.7 on 2025-09-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_make_address_optional'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE orders_product ADD COLUMN IF NOT EXISTS main_image bytea",
                    reverse_sql="ALTER TABLE orders_product DROP COLUMN IF EXISTS main_image",
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name='product',
                    name='main_image',
                    field=models.BinaryField(blank=True, editable=True, null=True),
                ),
            ],
        ),
    ]
