# Generated by Django 4.2.7 on 2025-09-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_make_address_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
